// One listable phase context: the addressable, titled record that replaced a filename which had to be
// renamed to change state. Every count is DERIVED from `messages` on read -- there are no stored
// counters to fall out of step with the turns they count.

/**
 * One listable phase context: the addressable, titled record. Every count is DERIVED from `messages`
 * on read — no stored counters to fall out of step. `title` is null until the throwaway one-shot has
 * written one (and stays null for a context that never produced a prose answer).
 */
export interface ContextSummary {
  /** The context's UUID (generated by SQLite). `shortContextId` renders the address form. */
  readonly id: string;
  readonly phase: string;
  readonly title: string | null;
  /** ISO-8601 UTC when the context was created. */
  readonly createdAt: string;
  /** Newest turn's timestamp, falling back to `createdAt` for a context with no turns. */
  readonly lastActivityAt: string;
  /**
   * The EXACT `OLLAMA_NUM_CTX` this context was WRITTEN under — a fact about the row, never about the
   * session reading it. A context is listed and reopenable while this is at or below the session's
   * ceiling; a value BELOW it means the history was written to fit a smaller window, which is what
   * `/resume` marks in the listing and warns about on the restore. A value above it never reaches a
   * caller: those contexts are filtered out (see memory-db.listContexts).
   */
  readonly numCtx: number;
  /** Visible turns (turns a summary has collapsed do not count). */
  readonly turnCount: number;
  /** Sum of every turn's prompt + completion tokens, `null` treated as 0 — a display total only. */
  readonly totalTokens: number;
  /** Distinct models that generated turns in this context, oldest first; empty for a context of none. */
  readonly models: readonly string[];
}
