// Types for the SQLite-backed phase memory. Kept in a sibling `.type.ts` per the constitution (types
// live beside the module they serve, never inline with a function).
//
// MemoryRecord is the IN-RAM shape of one turn and the unit SessionMemory buffers between flushes. It
// carries `seq` — the ordinal inside its context, assigned in RAM — rather than the row's UUID: the
// UUID is generated by SQLite on insert, so it does not exist while a turn is still buffered, and
// nothing in the live view needs it. `seq` is also what addresses a turn for the summary collapse.

import type { ToolCall } from '../llm/index.js';

/**
 * The role of a stored turn. `user | assistant | tool` are the live conversation; `summary` is written
 * by the summarization failsafe to collapse older turns. Mirrored by a CHECK constraint on
 * `messages.role`, so an unknown role is rejected by the database rather than stored and puzzled over.
 */
export type MemoryRole = 'user' | 'assistant' | 'tool' | 'summary';

/** EXACT Ollama counts for one turn — `null` means the metric was genuinely absent, never estimated. */
export interface TurnTokens {
  readonly prompt: number | null;
  readonly completion: number | null;
}

/**
 * One turn of a phase context, in RAM. `tokens` are the EXACT Ollama counts for the turn that produced
 * it (`prompt_eval_count`→`prompt`, `eval_count`→`completion`); user and tool turns carry `null`/`null`
 * because no generation produced them (constitution: token counts are always exact).
 */
export interface MemoryRecord {
  /** 1-based ordinal within the context — assigned in RAM, unique per context (`UNIQUE (context_id, seq)`). */
  readonly seq: number;
  /** ISO-8601 UTC of when the turn HAPPENED (not when it was flushed — a flush lags the turn). */
  readonly ts: string;
  readonly role: MemoryRole;
  readonly content: string;
  /** The model that GENERATED this turn; absent on user/tool turns, which no generation produced. */
  readonly model?: string;
  /** The assistant's issued tool calls, when the turn made any. */
  readonly tool_calls?: ToolCall[];
  /** For `role: "tool"` records, which tool produced the result. */
  readonly tool_name?: string;
  readonly tokens: TurnTokens;
  /** `seq` of the `summary` turn that collapsed this one; absent while the turn is still visible. */
  readonly replacedBySeq?: number;
}

/**
 * One listable phase context: the addressable, titled record. Every count is DERIVED from `messages`
 * on read — no stored counters to fall out of step. `title` is null until the throwaway one-shot has
 * written one (and stays null for a context that never produced a prose answer).
 */
export interface ContextSummary {
  /** The context's UUID (generated by SQLite). `shortContextId` renders the address form. */
  readonly id: string;
  readonly phase: string;
  readonly title: string | null;
  /** ISO-8601 UTC when the context was created. */
  readonly createdAt: string;
  /** Newest turn's timestamp, falling back to `createdAt` for a context with no turns. */
  readonly lastActivityAt: string;
  /** Visible turns (turns a summary has collapsed do not count). */
  readonly turnCount: number;
  /** Sum of every turn's prompt + completion tokens, `null` treated as 0 — a display total only. */
  readonly totalTokens: number;
  /** Distinct models that generated turns in this context, oldest first; empty for a context of none. */
  readonly models: readonly string[];
}

/**
 * Outcome of a `/clear`: the phase cleared, and the context it set aside so the command can name what
 * `/resume` would reopen. `cleared` is null when the phase had no persisted context to set aside —
 * a context is only created once the model actually answers, so an untouched phase has none.
 */
export interface ClearResult {
  readonly phase: string;
  readonly cleared: ContextSummary | null;
}

/**
 * What reopening a context reports back, so the orchestrator can emit a `memory_load` event.
 * `lastPromptTokens` is the most recent persisted prompt_eval_count — the EXACT restored context size
 * — or null if none was ever recorded (never estimated).
 */
export interface PhaseLoad {
  readonly contextId: string;
  /** Visible turns rebuilt into the prompt by the reopen. */
  readonly turns: number;
  readonly lastPromptTokens: number | null;
}
