// The SQLite schema behind a project's phase memory. Kept in a sibling `.schema.ts` per the
// constitution (schemas live beside the module they serve, never inline with a function).
//
// Two tables. `contexts` is one row per phase context — the addressable, titled record; `messages` is
// one row per turn inside a context. Both keys are UUIDs generated BY SQLITE via a column DEFAULT, so
// an id exists even for a row inserted by hand at a `sqlite3` prompt; memory-db.ts reads the generated
// value back with RETURNING rather than pre-computing one, which would make the DEFAULT decorative.
//
// SQLite ships no uuid(): SQL_UUID4 is the standard randomblob() construction, and it produces a
// CANONICAL v4 (the literal '4' version nibble, the variant nibble drawn from '89ab') rather than 32
// loose hex characters — verified against /^[0-9a-f]{8}-…-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-…$/.

/** A canonical UUIDv4 as a SQL expression — the DEFAULT behind both tables' `id`. */
export const SQL_UUID4 =
  "lower(hex(randomblob(4))||'-'||hex(randomblob(2))||'-4'||substr(hex(randomblob(2)),2)||'-'||" +
  "substr('89ab',abs(random())%4+1,1)||substr(hex(randomblob(2)),2)||'-'||hex(randomblob(6)))";

/** UTC ISO-8601 with milliseconds — byte-identical to `new Date().toISOString()`, so both sources agree. */
export const SQL_NOW = "strftime('%Y-%m-%dT%H:%M:%fZ','now')";

/**
 * Connection pragmas, applied on every open (they are per-connection, not stored in the file):
 * - `foreign_keys` is OFF by default in SQLite, so the messages→contexts reference is unenforced
 *   without this — the one pragma whose absence would silently permit orphan rows.
 * - `synchronous = FULL` fsyncs on each commit, matching the durability the JSONL store got from
 *   fsync-per-row: what has been written is on the platter even if the box loses power.
 */
export const MEMORY_PRAGMAS = `
PRAGMA foreign_keys = ON;
PRAGMA journal_mode = WAL;
PRAGMA synchronous = FULL;
`;

/**
 * The tables, indexes and triggers, all `IF NOT EXISTS` so opening an existing DB is a no-op.
 *
 * `contexts.num_ctx` is the EXACT `OLLAMA_NUM_CTX` the context was written under. A context written
 * under a different ceiling is hidden from every listing (never deleted — memory-db.ts filters on this
 * column), because Ollama silently drops the oldest tokens past `num_ctx`: replaying a 32k history
 * into an 8k window loses turns with no error, and a phase that resumed one would be reasoning from a
 * history it cannot actually see.
 *
 * `messages.replaced_by` points at the `summary` turn standing in for a collapsed one, so the visible
 * history is `WHERE replaced_by IS NULL` — one indexable predicate rather than a JSON array parsed and
 * walked in JS. `messages.model` is the model that GENERATED the turn; user and tool rows carry NULL
 * because no generation produced them, the same rule the token columns follow.
 *
 * The `*_touch` triggers maintain `updated_at`. Each UPDATEs its own table, which does not recurse:
 * SQLite's `recursive_triggers` is OFF by default and this code never turns it on.
 */
export const MEMORY_SCHEMA = `
CREATE TABLE IF NOT EXISTS contexts (
  id         TEXT    NOT NULL PRIMARY KEY DEFAULT (${SQL_UUID4}),
  phase      TEXT    NOT NULL,
  title      TEXT,
  num_ctx    INTEGER NOT NULL,
  created_at TEXT    NOT NULL DEFAULT (${SQL_NOW}),
  updated_at TEXT    NOT NULL DEFAULT (${SQL_NOW})
);

CREATE INDEX IF NOT EXISTS contexts_by_phase ON contexts (phase, created_at);

CREATE TRIGGER IF NOT EXISTS contexts_touch AFTER UPDATE ON contexts BEGIN
  UPDATE contexts SET updated_at = ${SQL_NOW} WHERE id = NEW.id;
END;

CREATE TABLE IF NOT EXISTS messages (
  id                TEXT    NOT NULL PRIMARY KEY DEFAULT (${SQL_UUID4}),
  context_id        TEXT    NOT NULL REFERENCES contexts(id) ON DELETE CASCADE,
  seq               INTEGER NOT NULL,
  role              TEXT    NOT NULL CHECK (role IN ('user', 'assistant', 'tool', 'summary')),
  content           TEXT    NOT NULL,
  model             TEXT,
  tool_name         TEXT,
  tool_calls        TEXT,
  prompt_tokens     INTEGER,
  completion_tokens INTEGER,
  replaced_by       TEXT    REFERENCES messages(id),
  created_at        TEXT    NOT NULL DEFAULT (${SQL_NOW}),
  updated_at        TEXT    NOT NULL DEFAULT (${SQL_NOW}),
  UNIQUE (context_id, seq)
);

CREATE INDEX IF NOT EXISTS messages_visible ON messages (context_id, seq) WHERE replaced_by IS NULL;

CREATE TRIGGER IF NOT EXISTS messages_touch AFTER UPDATE ON messages BEGIN
  UPDATE messages SET updated_at = ${SQL_NOW} WHERE id = NEW.id;
END;
`;
