// One turn of a phase context, IN RAM -- the unit SessionMemory buffers between flushes.
//
// It carries `seq`, the ordinal inside its context assigned in RAM, rather than the row's UUID: the
// UUID is generated by SQLite on insert, so it does not exist while a turn is still buffered, and
// nothing in the live view needs it. `seq` is also what addresses a turn for the summary collapse.

import type { ToolCall } from 'ollama';

import type { MemoryRole } from './memory-role.type.js';
import type { TurnTokens } from './turn-tokens.type.js';

/**
 * One turn of a phase context, in RAM. `tokens` are the EXACT Ollama counts for the turn that produced
 * it (`prompt_eval_count`→`prompt`, `eval_count`→`completion`); user and tool turns carry `null`/`null`
 * because no generation produced them (constitution: token counts are always exact).
 */
export interface MemoryRecord {
  /** 1-based ordinal within the context — assigned in RAM, unique per context (`UNIQUE (context_id, seq)`). */
  readonly seq: number;
  /** ISO-8601 UTC of when the turn HAPPENED (not when it was flushed — a flush lags the turn). */
  readonly ts: string;
  readonly role: MemoryRole;
  readonly content: string;
  /** The model that GENERATED this turn; absent on user/tool turns, which no generation produced. */
  readonly model?: string;
  /** The assistant's issued tool calls, when the turn made any. */
  readonly tool_calls?: ToolCall[];
  /** For `role: "tool"` records, which tool produced the result. */
  readonly tool_name?: string;
  readonly tokens: TurnTokens;
  /** `seq` of the `summary` turn that collapsed this one; absent while the turn is still visible. */
  readonly replacedBySeq?: number;
  /**
   * ISO-8601 UTC of when the user cancelled the exchange this turn belongs to; absent for every turn
   * that was not cancelled. The second reason a turn leaves the live history — see the schema's note.
   * A cancelled turn is hidden, never deleted: the exchange is branched off so the prompt can be
   * rewritten, and stays on disk for audit.
   */
  readonly cancelledAt?: string;
}
